### ISSUE TITLE
Fails install on VS 2013 Pro.

### ISSUE THREAD

**Issue by reltham** [tgjones/HlslTools#1]
Attempting to install into VS 2013 Pro (Update 5). Fails with dialog saying "This extension is not installable on any currently installed products."

Error spew from installer:

10/6/2015 1:30:11 PM - Microsoft VSIX Installer
10/6/2015 1:30:11 PM - -------------------------------------------
10/6/2015 1:30:11 PM - Initializing Install...
10/6/2015 1:30:12 PM - Extension Details...
10/6/2015 1:30:12 PM - 	Identifier      : 7def6c01-a05e-42e6-953d-3fdea1891737
10/6/2015 1:30:12 PM - 	Name            : HLSL Tools for Visual Studio
10/6/2015 1:30:12 PM - 	Author          : Tim Jones
10/6/2015 1:30:12 PM - 	Version         : 0.9.10
10/6/2015 1:30:12 PM - 	Description     : Enhanced support for editing HLSL in Visual Studio
10/6/2015 1:30:12 PM - 	Locale          : en-US
10/6/2015 1:30:12 PM - 	MoreInfoURL     : https://github.com/tgjones/HlslTools
10/6/2015 1:30:12 PM - 	InstalledByMSI  : False
10/6/2015 1:30:12 PM - 	SupportedFrameworkVersionRange : [4.5,)
10/6/2015 1:30:12 PM - 
10/6/2015 1:30:12 PM - 	Supported Products : 
10/6/2015 1:30:12 PM - 		Microsoft.VisualStudio.Community
10/6/2015 1:30:12 PM - 			Version : [12.0,15.0)
10/6/2015 1:30:12 PM - 
10/6/2015 1:30:12 PM - 	References      : 
10/6/2015 1:30:12 PM - 		-------------------------------------------------------
10/6/2015 1:30:12 PM - 		Identifier   : Microsoft.VisualStudio.MPF.12.0
10/6/2015 1:30:12 PM - 		Name         : Visual Studio MPF 12.0
10/6/2015 1:30:12 PM - 		Version      : [12.0]
10/6/2015 1:30:12 PM - 		MoreInfoURL  : 
10/6/2015 1:30:12 PM - 		Nested       : No
10/6/2015 1:30:12 PM - 
10/6/2015 1:30:12 PM - 
10/6/2015 1:30:12 PM - Searching for applicable products...
10/6/2015 1:30:12 PM - Found installed product - Microsoft Visual Studio 2010 Professional
10/6/2015 1:30:12 PM - Found installed product - Microsoft Visual Studio Professional 2013
10/6/2015 1:30:12 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
10/6/2015 1:30:12 PM - Found installed product - Global Location
10/6/2015 1:30:12 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by tgjones** [comment]
Thanks for reporting this. I'd thought that setting `InstallationTarget` to "Microsoft.VisualStudio.Community" would work for all non-Express versions, but turns out that wasn't the case. According to some StackOverflow answers, "Microsoft.VisualStudio.Pro" is the correct one - and it works for Community too - so I've changed it to that.
