### ISSUE TITLE
Hlsl continue statement crashes Visual Studio 2017

### ISSUE THREAD

**Issue by TimmehT** [tgjones/HlslTools#101]
For some reason simply writing "continue;" to return back to the top of a loop with the extension turned on causes VS 2017 to crash. This also happens when I enter "continue" into my code with the extension turned off and then turn it  back on upon restarting VS it will crash when opening the shader file that contains "continue"

**Comment by tiiago11** [comment]
I'm experiencing the same issue here.

**Comment by tgjones** [comment]
Thanks for reporting this - fixed.
