### ISSUE TITLE
Always replaces tabs with spaces (ignoring settings)

### ISSUE THREAD

**Issue by rbmkp4800** [tgjones/HlslTools#103]
Clean Visual Studio 2017 installation (no other extensions installed)
It ignores setting and always uses spaces instead of tabs
Entire file autoformatting works in the same way
But if I select text block indent it to left/right (Shift+Tab/Tab) it works correct
Sometimes it crashes visual studio

**Comment by ylqgithubylq** [comment]
I have the same problem.
When have Productivity Power Tools extension installed, that's quite annoying as it constantly prompt to fix mixed tabs and spaces.

Hope it will be fixed.

**Comment by Lex-DRL** [comment]
The same problem, VS 2015 Community Update 3.
So far I fixed it by completely disabling any indentation fixes. I.e., `Tools -> Options -> Text Editor -> HLSL`:
1. Switch Indenting to Block under `Tabs` section.
2. Disable all three auto-formats under `Formatting -> General` subsection.

**Comment by tgjones** [comment]
Fixed by #171.
