### ISSUE TITLE
 Bug of  copying? 

### ISSUE THREAD

**Issue by 404517981** [tgjones/HlslTools#104]
When I copy string ，it show  invalid conversion.

**Comment by 404517981** [comment]
Mabey it's a bug,who know.(^_^)!

**Comment by tgjones** [comment]
Can you show some code that demonstrates the error?

**Comment by 404517981** [comment]
The symbol ；can make a error and pop a  message box from vs .I'm sorry ,I dont remind the
error.its to long

**Comment by tgjones** [comment]
Closing this for now, but if you have a snippet of code that can reproduce this error, please re-open.
