### ISSUE TITLE
Program breaks down when typing "technique11" in vs2017

### ISSUE THREAD

**Issue by maplefox** [tgjones/HlslTools#105]
I'm using this tools to write effect files.
It seems this tool only support raw hlsl edition.
And when I have just typed "technique11",this plug-in crash with the host vs.
Just typing a word the program will crash,I hope this bug can be fixed.

**Comment by stilldesign** [comment]
> And when I have just typed "technique11",this plug-in crash with the host vs.

I'm also experiencing this issue - apart from this, nice extension :)

**Comment by tgjones** [comment]
Thanks for reporting this - fixed.
