### ISSUE TITLE
Parsing characters literals

### ISSUE THREAD

**Issue by bhnascar** [tgjones/HlslTools#107]
I read that this plugin has a custom HLSL parser; I'm guessing that has something to do with this (false) Intellisense warning regarding character literals:

![parse_error](https://user-images.githubusercontent.com/1694743/28987823-c9258ab2-7921-11e7-8551-be6ba07397f2.png)

We have a custom debug log utility built on top of character literals, which is used in a lot of places, and would love to see all the red squiggles go away.

**Comment by tgjones** [comment]
I had no idea until you reported this that HLSL even had character literals :) Fixed now.
