### ISSUE TITLE
Inline keyword

### ISSUE THREAD

**Issue by VirusFree** [tgjones/HlslTools#11]
does not recognize the "inline" keyword

**Comment by tgjones** [comment]
Oops, not sure how I missed that. Thanks.

Incidentally, `inline` has no effect, as [this page on MSDN rather awkwardly states](https://msdn.microsoft.com/en-us/library/windows/desktop/bb509607%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396):

> StorageClass: Modifier that redefines a function declaration. inline is currently the only modifier value. The modifier value must be inline because it is also the default value. Therefore, a function is inline regardless of whether you specify inline, and all functions in HLSL are inline. An inline function generates a copy of the function body (when compiling) for each function call. This is done to decrease the overhead of calling the function.

In any case, `inline` is valid HLSL, so I'll add it.
