### ISSUE TITLE
FindInstalledExtension-task failed unexpectedly

### ISSUE THREAD

**Issue by MarkusMiller** [tgjones/HlslTools#117]
Hello,
yes, I saw the previous issue but unfortunately I didn't receive any response on this one. So - yeah, I'm receiving the same error. The extension sdk is installed (if I open the project without installed extension sdk, only 28 projects are loaded, but it compiles without issues, once I reinstall the extension sdk, 31 projects are loaded and only a single one is failing. That's the error I'm receiving:

Unerwarteter Fehler bei der FindInstalledExtension-Aufgabe.
System.Runtime.InteropServices.COMException (0x800700B7): ExternalSettingsManager::GetScopePaths failed to initialize PkgDefManager for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe
   bei Microsoft.VisualStudio.Settings.ExternalSettingsManager.GetScopePaths(String applicationPath, String suffixOrName, String vsVersion, Boolean isLogged, Boolean isForIsolatedApplication)
   bei Microsoft.VisualStudio.Settings.ExternalSettingsManager.CreateForApplication(String applicationPath, String rootSuffix, IInteropLogger logger)
   bei Microsoft.VsSDK.Build.Tasks.ExtensionManagerUtilities.GetSettingsManagerForDevenv(String rootSuffix)
   bei Microsoft.VsSDK.Build.Tasks.FindInstalledExtension.Execute()
   bei Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   bei Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

Also, I first ran into this problem when I tried to build a GLSL fork of the HLSLTools. Then I wanted to check if it occurs with the HLSLTools as well and here we are. Seems like I'm missing another extension (which one)?

Would be really great if you could provide some advice.

Kind regards

Markus

**Comment by tgjones** [comment]
I'm not getting this error when building. Has anything magically changed since February so that it builds successfully for you now?

**Comment by MarkusMiller** [comment]
Hey,

thanks for your reply. Probably not, but I'll check tomorrow my other computer and get back to you.

**Comment by MarkusMiller** [comment]
Hey,
nah, doesn't work. However, after pulling your current git content, it fails now due to a missing project. $(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets is missing, referenced from ShaderTools.Editor.VisualStudio.Tests

however, I double checked if the Visual Studio SDK is installed (I reinstalled it)

**Comment by tgjones** [comment]
@MarkusMiller are you still getting this issue with the latest source code? I was, including on AppVeyor, but I'm not now.

**Comment by MarkusMiller** [comment]
I'll check tomorrow and get back to you. Thanks for your help
