### ISSUE TITLE
Any new updates, Unity more specifically.

### ISSUE THREAD

**Issue by xCyborg** [tgjones/HlslTools#118]
Development here seems to have stalled for quite some time, nothing on the *unity* branch for over two years.

**Comment by DesigningKnights** [comment]
Wondering myself if any progress on ShaderLab support? been a long time now

**Comment by tgjones** [comment]
I'm picking up development on this, but my time is very limited so (unfortunately) I need to focus on just the HLSL parts for now.

I'd love to add ShaderLab support, but it turned out to be a huge amount of work, some of which I've done, plenty of which remains to be done.
