### ISSUE TITLE
Not handling # operator (stringification) in preprocesser macros

### ISSUE THREAD

**Issue by reltham** [tgjones/HlslTools#12]
Example macro:
```C
#define TEX_COMP_FULL(format, packed) string Build_TexComp_DdsFormat = #format; string Build_TexComp_IsPacked = #packed
```
Example usage:
```C
TEX_COMP_FULL(dxt5, true);
```
Reports all these errors for the same line and column:
Error	1	Invalid expression term '#'.
Error	2	Found '#' but expected '<identifier>'.
Error	3	Found '#' but expected ';'.
Error	4	Found 'dxt5' but expected '>'.
Error	5	Unexpected token 'dxt5'.
Error	6	Unexpected token '#'.
Error	7	Invalid expression term '#'.
Error	8	Found '#' but expected '<identifier>'.
Error	9	Found '#' but expected ';'.	
Error	10	Unexpected token '#'.

**Comment by reltham** [comment]
I think the column part of errors is not right, it appears to be related to lines and ever growing.

**Comment by tgjones** [comment]
I was actually waiting to see if anyone needed the `#` operator, before implementing it. So... I guess I have an answer :)

**Comment by tgjones** [comment]
I've implemented the stringification operator. By the way, the above snippet won't work, because it's missing the closing semicolon at the end of the macro body (I assume that's a copy-and-paste glitch). This works, though:

``` c
#define TEX_COMP_FULL(format, packed) string Build_TexComp_DdsFormat = #format; string Build_TexComp_IsPacked = #packed;
Texture2D MyTex < TEX_COMP_FULL(dxt5, true) >;
```

**Comment by reltham** [comment]
Yeah, I didn't include the wrapped around the usage case, which is similar to your example usage, just with more stuff between the <>'s.
