### ISSUE TITLE
Please ignore Raw string literals.

### ISSUE THREAD

**Issue by DaveHoskins** [tgjones/HlslTools#126]
Hi, I'd like to #include my shaders with my source code, unfortunately I can't put 
**R"(** and **)"** around my shader because the syntax high-lighting gets completely removed.
Is there anyway it can just ignore the **R"(** at the start of the code?
Thanks.

**Comment by tgjones** [comment]
Do you mean you're adding `R"(` and `)"` in HLSL code, or C++ code? I didn't think HLSL supports raw string literals, so I'm closing this for now, but please re-open if it does in fact support raw string literals.

**Comment by DaveHoskins** [comment]
> Do you mean you're adding `R"(` and `)"` in HLSL code, or C++ code? I didn't think HLSL supports raw string literals, so I'm closing this for now, but please re-open if it does in fact support raw string literals.

This is in C++, I'm including the HLSL code as an 'h' file but with the appropriate file extension. To do that in C++ you have to have those simbols around the code..Like so...

R"(

#version 120
uniform sampler2D texture0;
varying vec2 texCoord;
void main(void)
{
    vec3 col = texture2D(texture0, texCoord).xyz;
	gl_FragDepth = 1.0;
	gl_FragColor = vec4(col, 1.0);
}
)"

**Comment by PathogenDavid** [comment]
I get what you're trying to do, but that's pretty strange. Those aren't valid HLSL files anymore.

I feel like most large-scale projects precompile their shaders and load them from the filesystem. If you really want to avoid that for whatever reason, you should embed them as resources in the executable.

**Comment by tgjones** [comment]
@DaveHoskins can you `#include` the shader code like this, so that you can still edit the shader as a standalone file?

``` c
R"(
#include "myshader"
)"
```

By the way, the shader code you included is GLSL, but maybe that was just as an example.

**Comment by DaveHoskins** [comment]
Nevermind, it's part of c++11, a feature called raw string literals. Like I said, nevermind, I'll do it another way. : )
