### ISSUE TITLE
Implement keyword completion

### ISSUE THREAD

**Issue by Alan-FGR** [tgjones/HlslTools#128]
When you type `if(` or even `if ` (space), the code turns into `ProcessIsolineTessFactors`, so in order to properly type an `if` you have to either disable Intellisense altogether or remember to type `ESC` right after typing `if`. Now `if` is a pretty common keyword, it should be supported by the tool and should be on top of the Intellisense list. Every time I type an `if` it changes into something I don't want, that bothered me so much that I've disabled the feature altogether but then Notepad++ provides better coding capabilities. Other than that this tool is good and definitely keep up the good work! Too bad there's no official support from MS for a tool like this.

**Comment by mrvux** [comment]
Actually that can be extended to other flow control keywords as well: 
if / while / for 

And in your case, since "if" is not even part of ProcessIsolineTessFactors, intellisense should not even activate.

Tried it with other keywords , we have : 
w -> AllMemoryBarrierWithGroupSync
wh -> stays as it

for -> stays as is

**Comment by Const-me** [comment]
Same with `const ` 
The extension replaces it with ConstructGSWithSO.

**Comment by Alan-FGR** [comment]
:rofl: relevant username

**Comment by Const-me** [comment]
@Alan-FGR My first name, and `me` is country suffix (both ISO 3166 and Internet TLD).

Coincidentally, I like `const` in the languages I write (C++, C#, HLSL): the compiler authors were nice enough to implement this extra level of compile-time verification, no reason not to use the feature.

**Comment by reltham** [comment]
This is one of the most annoying things in this extension.  I am considering dumping the whole thing over this.

**Comment by Vastrix** [comment]
Please :(

**Comment by tgjones** [comment]
Fixed by 5ccf2d0e041442c6f3e80349af27b47caf57261e
