### ISSUE TITLE
Properties Panel no longer populating

### ISSUE THREAD

**Issue by h1cks** [tgjones/HlslTools#129]
1. Select type of content to be Vertex Shader/Pixel etc. 
2. Properties field changes to empty, no fields available.
3. If file was previously selected as a vertex shader etc, it compiles, but you can not update the properties through the UI.  Editing the solution XML allows for updates still. 

This problem has occurred in only the past few releases of VS 2017 community, and looks like a compatibility issue has come from various updates. 

I have also checked the language options and believe this also doesn't show up.

Maybe a simple fix, have checked a number of forks and some issues seems to of been fixed.

Pulled the code, but unable to understand the build process to create a new package to install (my problem).  Would appreciate if this tool is updated/fixed to work once again with VS as it is invaluable.

**Comment by h1cks** [comment]
@tgjones - thank you for your efforts on this tool.

**Comment by tgjones** [comment]
First, sorry for the huge delay in replying. I've no idea if you are still interested in getting this fixed, but on the offchance you are: I've just tried repro'ing this, but I can't - when I change the shader type, it continues working correctly. Is it still not working for you?

**Comment by tgjones** [comment]
Closing this for now, but @h1cks please re-open if it's still an issue.

**Comment by h1cks** [comment]
@tgjones thanks mate, I've been using it even with the issue, I just edit the XML in the project file.  I would be keen to see documentation on what other XML tags can be set manually in the project.  Apologies, this alert to me never came up,  so when I went searching for updates to the tool . I found my original report with my fail to respond.

**Comment by h1cks** [comment]
I've uploaded a snapshot of the empty properties list.  
![image](https://user-images.githubusercontent.com/17155885/147727360-95d37e17-5cc0-44be-9c47-f03c43432541.png)
Thanks!

**Comment by h1cks** [comment]
> Closing this for now, but @h1cks please re-open if it's still an issue.

Love this tool btw .  gw.
