### ISSUE TITLE
Implement DXR intrinsics

### ISSUE THREAD

**Issue by windr00** [tgjones/HlslTools#133]
I have tried to do this myself by adding dxr related function intrinsics in to `IntrinsicFunctions.cs` under `ShaderTools.CodeAnalysis.Hlsl` project. I built it and installed into VS 2017 Community, but it doesn't seem to work at all.

I'm totally new to Visual Studio Extension Development. Can anyone help with this enhancement ?

**Comment by windr00** [comment]
By `it doesn't seem to work at all`, I mean it looks like the whole plugin is not loaded. (or unloaded due to errors)

**Comment by AdamJMiles** [comment]
Confirmed. The plugin fails to load (or unloads itself pretty quickly

![image](https://user-images.githubusercontent.com/18439438/61290268-61a25280-a7c3-11e9-8e46-d3fe9d31f56f.png)

**Comment by tgjones** [comment]
@ajmiles please could you paste the contents of the ActivityLog.xml mentioned in the dialog?
