### ISSUE TITLE
Update on ShaderLab

### ISSUE THREAD

**Issue by xCyborg** [tgjones/HlslTools#134]
Hi, is this extension still alive? if so will there ever be Unity shader support?

**Comment by tgjones** [comment]
I have already done a lot of the work required to support ShaderLab. However, "real life" has intervened and I don't currently have time to work on HLSL Tools at all. I'm hoping this will change and I'll be able to finish and release a version with ShaderLab support, but that's the situation at the moment.

**Comment by xCyborg** [comment]
I understand, thanks for the effort, it's just that there's not much choices out there.
Good luck and if there's anything I can help with I'm always available.
