### ISSUE TITLE
Building from source in visual studio fails

### ISSUE THREAD

**Issue by mrvux** [tgjones/HlslTools#138]
Since I posted that issue in Gitter, it makes sense to post it here.

Happens from a fresh clone, Visual Studio (2017 community here) fails to load SyntaxGenerator, as it cant load netstandard 2.0 assemblies

**Comment by tgjones** [comment]
As a temporary workaround until I can find something better, it looks like you need to:

* load the solution and right-click Build the SyntaxGenerator project
* close and reload the solution, and now it should build

**Comment by tgjones** [comment]
It's not great, but I've found that if I open Task Manager and close all instances of MSBuild.exe, then I can build the solution successfully in both VS2017 and VS2019.

Curiously, though, I haven't seen any errors about netstandard2.0 assemblies. Let me know if you still get this.
