### ISSUE TITLE
After HLSL tools is enabled, Visual Studio's "structure guide lines" disappear

### ISSUE THREAD

**Issue by AdamJMiles** [tgjones/HlslTools#139]
![image](https://user-images.githubusercontent.com/18439438/60663020-f026e380-9e55-11e9-963b-d3a21120286b.png)

Prior to installing and enabling HLSL Tools these dashed lines appeared in HLSL files as well. Now that I've installed HLSL Tools again these lines have disappeared in .hlsl files.

The Visual Studio option for "Show structure guide lines" (Tools -> Text Editor -> General) is still enabled, but they're no longer working in .hlsl files!

![image](https://user-images.githubusercontent.com/18439438/60663347-dfc33880-9e56-11e9-91cf-9259ba24566f.png)

Thanks,

Adam

**Comment by tgjones** [comment]
This belongs in the category of "built-in, but as soon as you provide your own language service you have to write it from scratch", which includes things like formatting, indentation, syntax highlighting, etc. Anyway, it wasn't too hard to reuse the work I'm already doing to provide outlining to also do the right thing for structure tagging, as it's called:

<img width="395" alt="structure" src="https://user-images.githubusercontent.com/102049/60687708-3442d400-9ea8-11e9-9848-fc17c30d4378.PNG">
