### ISSUE TITLE
F1 context help does not work (works as soon as tool is diabled/uninstalled)

### ISSUE THREAD

**Issue by mr-phazer** [tgjones/HlslTools#158]
When I don't have your excellent, i must say, tool extension installed I can place the cursor on HLSL keywords, press F1 and get the exact page I need, but WITH your extension installed, when I do that same I get directed to a page:
https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/default?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.TextEditor)%26rd%3Dtrue&view=vs-2019

That says it could not find the keyword anywhere, it seems the problem it that the search function does not get a keyword, or it gets something different :(

**Comment by tgjones** [comment]
Thanks for reporting this - apologies it's taken so long to reply. I'm going to have a go at implementing this. It seems that VS extensions need to include specific support for F1 context help, it's not something that comes "for free".
