### ISSUE TITLE
Problems with ## in macro body

### ISSUE THREAD

**Issue by reltham** [tgjones/HlslTools#16]
These macros:
```C
#define JUST_PS_TECH_FULL(name, channels, uvchannels, outputfunc, state) float4 PS_Just##name(PS_INPUT IN): COLOR { \
	float4 alpha = 1; \
	alpha.channels = tex2D(g_##name##Sampler, IN.##uvchannels ).channels; \
	return float4(outputfunc((float3)tex2D(g_##name##Sampler, IN.##uvchannels ).channels), alpha.a); } \
technique Just##name {  pass p0 { state \
	Vertexshader = compile vs_3_0 VS_Default();	 pixelshader = compile ps_3_0 PS_Just##name(); }}

#define JUST_PS_TECH(name, channels, uvchannels) JUST_PS_TECH_FULL(name, channels, uvchannels, Float3PassthroughFunc, AlphaBlendEnable = false;)
```

Example Usage:
```C
JUST_PS_TECH(Color, rgb, v4TexCoords.xy);
```

Reports these errors for any line attempting to use JUST_PS_TECH(...):
Error	254	Found '##' but expected ')'.
Error	255	Found '##' but expected ';'.
Error	256	Unexpected token '##'.
Error	257	Found '##' but expected '}'.
Error	258	Found ',' but expected ';'.
Error	259	Unexpected token ','.
Error	260	Found ',' but expected '}'.
Error	261	Unexpected token '.'.
Error	262	Found ')' but expected ';'.
Error	263	Unexpected token ')'.
Error	264	Found ')' but expected '}'.
Error	265	Found ';' but expected '<identifier>'.
Error	266	Found '##' but expected ')'.
Error	267	Found '##' but expected ')'.
Error	268	Found '##' but expected ')'.
Error	269	Found '##' but expected ';'.
Error	270	Unexpected token '##'.
Error	271	Found '##' but expected '}'.
Error	272	Found ',' but expected ';'.
Error	273	Unexpected token ','.
Error	274	Found ',' but expected '}'.
Error	275	Unexpected token '.'.
Error	276	Found ')' but expected ';'.
Error	277	Unexpected token ')'.
Error	278	Found ')' but expected '}'.
Error	279	Found ')' but expected ';'.
Error	280	Unexpected token ')'.
Error	281	Found ')' but expected '}'.
Error	282	Unexpected token ')'.

**Comment by tgjones** [comment]
There was a flaw in how I implemented the token pasting operator; token pasting should have been done before parameters in the macro body are replaced with argument values - but it was only noticeable when argument values contained more than one token. I've fixed it now.
