### ISSUE TITLE
Extension does not start on VS Code

### ISSUE THREAD

**Issue by BSG-75** [tgjones/HlslTools#165]
VS Code shows that `The HLSL Tools Language Client server crashed 5 times in the last 3 minutes. The server will not be restarted.`
```
Error:
  An assembly specified in the application dependencies manifest (ShaderTools.LanguageServer.deps.json) was not found:
    package: 'runtimepack.runtime.win-x64.Microsoft.NETCore.App', version: '3.0.0-preview6-27804-01'
    path: 'api-ms-win-core-console-l1-1-0.dll'
[Error - 上午1:45:04] Connection to server got closed. Server will not be restarted.
```
![image](https://user-images.githubusercontent.com/2989995/62665087-466bd280-b97e-11e9-83a9-9035609dcde7.png)

HLSL Tools Extension Version: `1.0.4`
Visual Studio Code Version: ```Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134```

.NET Core 2.2 is installed on my computer (by typing `dotnet --version` it shows `2.2.102`)

**Comment by tgjones** [comment]
Thanks for logging this. This is weird because I'm using .NET Core 2.1, and building a standalone executable so it shouldn't care about what version(s) of .NET Core you have installed, but the error talks about .NET Core 3.0.0-preview6.

Did you install this from the Marketplace, or build it yourself?

**Comment by tgjones** [comment]
Closing this, but please re-open if you have repro steps.

**Comment by edensg** [comment]
I'm having this issue too - `The HLSL Tools Language Client server crashed 5 times in the last 3 minutes. The server will not be restarted.`

Error in VSCode (repeated 5x):

```
Error:
  An assembly specified in the application dependencies manifest (ShaderTools.LanguageServer.deps.json) was not found:
    package: 'runtime.win-x64.Microsoft.NETCore.App', version: '2.1.15'
    path: 'runtimes/win-x64/native/api-ms-win-core-console-l1-1-0.dll'
[Info  - 3:48:54 p.m.] Connection to server got closed. Server will restart.
```
Extension version: `v1.1.301`


VSCode version: 
```
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

Extension install from the extension gallery, I've tried reinstalls and the issue persists.
