### ISSUE TITLE
Typing 'if (' auto completes to IsFinite(

### ISSUE THREAD

**Issue by zachbethel** [tgjones/HlslTools#172]
I'm unable to type a basic if statement without the autocomplete coercing it to IsFinite(. Is there any way I can disable this?

**Comment by tgjones** [comment]
Please could you try the latest nightly build here, and see if it fixes your issue?

http://vsixgallery.com/extension/7def6c01-a05e-42e6-953d-3fdea1891737/

I believe it should be fixed already, please let me know. I need to release a new version to the Marketplace.

**Comment by tgjones** [comment]
Closing this because it's fixed in the latest version on VS Marketplace. Please re-open if it's still an issue.
