### ISSUE TITLE
Highlight matching parens feature

### ISSUE THREAD

**Issue by Reedbeta** [tgjones/HlslTools#175]
It would be nice for HLSL Tools to highlight matching parens, brackets, and braces when the cursor is placed on one of the pair, similar to VS and other editors.

**Comment by tgjones** [comment]
That sounds like a bug, because this should already work in HLSL Tools, in both VS and VSCode. Are you using VS? Does it not match braces at all?

**Comment by Reedbeta** [comment]
I'm using VS. It matches braces in C++, but I don't see any matching brace highlighting when I put the cursor next to a brace in HLSL at all.

**Comment by tgjones** [comment]
I notice the default brace highlight colour is a very light grey, but still, I'm definitely getting brace highlighting for parens, brackets, and braces. Which version of VS are you using? Is it still an issue?

**Comment by Reedbeta** [comment]
You're right! I had to look _really_ close to see it, the colors are so similar that it's almost impossible to tell, but the highlighting is there.

It's interesting that the highlight color is different for HLSL than for C++, though. I haven't made any changes to the colors, just using the default dark theme in VS (2019, now, though I saw this on 2017 first). Does the extension have any influence over those colors? Is it possible to change the default to match those for C++/C#?

**Comment by tgjones** [comment]
There was a bug in how I was doing brace highlighting, which meant the highlight colour couldn't be customised. I've fixed that now, so the "Brace Matching" colour will be applied to HLSL:

![image](https://user-images.githubusercontent.com/102049/71354377-a94bb800-2573-11ea-9043-91f5ff54859b.png)

**Comment by Reedbeta** [comment]
Awesome, thanks!
