### ISSUE TITLE
Nightly build version number is wrong

### ISSUE THREAD

**Issue by JSeb-92** [tgjones/HlslTools#177]
Hello,

I've tested you're nightly build version (1.1.2) and many bugs are fixes like hlsl keywords being known by your database, that's a good thing.
Yet, you may notice that this (last) version, made September 13 2019 has a smaller version number (1.1.2) than previous built version which is still on VSIX gallery (1.1.296 update 07/07/2019).
This is unfortunate since if you forget to unselect the "Automatically update this extension" VS's check box, the old one (with bugs) will (silently) replace the new one, after some VisualStudio starts.

Thanks

**Comment by tgjones** [comment]
I haven't figured out a good way to keep both VSIX Gallery and VS Marketplace versions up-to-date with sensible version numbers, so for now I'm not publishing to VSIX Gallery. I do plan to do more regular VS Marketplace releases though.
