### ISSUE TITLE
Fails to load on vs2015

### ISSUE THREAD

**Issue by sleepyspider1** [tgjones/HlslTools#178]
I can download the plugin for vs2015 and install it. But it dies when it loads.

Either prevent the install, stop it from showing up when you search the extensions with vs2015, or actually support 2015. The fact that you can download and install it on vs2015 makes it look like it should work. There's no indication that it isn't supported except on the github page where it only says vs2017/vs2019.

**Comment by tgjones** [comment]
Thanks for logging this. I have just released v1.1.300 to the Marketplace, which supports only VS2017 and VS2019.
