### ISSUE TITLE
Getting this error when trying to use hlsl tools

### ISSUE THREAD

**Issue by lifangjie** [tgjones/HlslTools#179]
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet'.
[Error - 下午10:32:04] Connection to server got closed. Server will not be restarted.

**Comment by tgjones** [comment]
Did you install the extension from within VSCode, or did you build it yourself? Which version of the extension do you have? I haven’t been able to repro this yet.

**Comment by tgjones** [comment]
Closing this because I can't repro, but please re-open if it's still an issue.
