### ISSUE TITLE
Undeclared identifiers are passing through syntax validation

### ISSUE THREAD

**Issue by mrvux** [tgjones/HlslTools#19]
If we take the following simple snippet

    float3 MyFunc(float3 test)
    {
        t = u;
        return test;
    }

This does not give any error message in the parser, but will provide a compilation error using D3DCompile (as both t and u are not declared yet).

**Comment by tgjones** [comment]
This is a "known issue" - HLSL Tools doesn't do any semantic analysis yet, so it doesn't pick up this kind of error. I do have semantic errors on the [roadmap](https://github.com/tgjones/HlslTools/blob/master/CHANGELOG.md), so I'll close this in favour of the existing roadmap item.
