### ISSUE TITLE
[Enhancement] Unity specific relative #include paths

### ISSUE THREAD

**Issue by Evurt** [tgjones/HlslTools#191]
Great work with the extension, it's truly amazing! There's one feature for me (and a lot of other users I'm betting) to be able to use it properly, and that's the unity specific relative #include paths. 

Any chance that such a feature could be added?

**Comment by tgjones** [comment]
Hi @Evurt, sorry for the massive delay in replying! I'm not sure if it's what you are looking for, but you can do this:

``` json
{
    "hlsl.preprocessorDefinitions": { },
    "hlsl.additionalIncludeDirectories": [
        "C:/Program Files/Unity/Hub/Editor/2020.1.9f1/Editor/Data/CGIncludes"
    ]
}
```

... and then you can include Unity files like this:

``` c
#include "UnityCG.cginc"
```

**Comment by tgjones** [comment]
Closing this in the hope that the above answers your question, but if not feel free to reopen.
