### ISSUE TITLE
Linux,Syntax highlighting is invalid

### ISSUE THREAD

**Issue by runner0353** [tgjones/HlslTools#192]
Ubuntu18.04,Colors cannot be displayed correctly, but other functions are effective
![test-hlsl](https://user-images.githubusercontent.com/36179001/82975370-d282df80-a00e-11ea-8b38-3c1eb42ecffa.png)

**Comment by tgjones** [comment]
@runner0353 my apologies for the huge delay in replying.

This is interesting - HLSL Tools for VSCode doesn't actually do any syntax highlighting. That is handled by something that's builtin to VSCode (which, as it happens, I did contribute to VSCode).

I've just tried that shader in VSCode on Windows, and syntax highlighting looks correct to me. So my guess is this is more of a VSCode issue, and perhaps not an HLSL grammar issue. Maybe report it directly to the VSCode repo?
