### ISSUE TITLE
keyboard key to edit

### ISSUE THREAD

**Issue by tankerpat** [tgjones/HlslTools#193]
Hi,
Sry in advance my english is really bad.

I can't modify my shader or my project after built it.
I need to wait few minutes, or
I need to restart VS, or
Sometimes I can select with the mouse,or
Sometimes CTRL+ k , CTRL + i, I don't know why but sometimes it works.

Key incriminated : 
ENTER, BACK, DELETE, ARROW KEY, TAB.

Windows10 last Update
Visual Studio 2017 with Monogame last release
Keyboard : AZERTY

**Comment by tgjones** [comment]
Hi @tankerpat - I'm sorry for the long delay in replying. Are you able to send me the shader(s) you were editing, when you experienced this issue? Is the main problem that Visual Studio becomes too slow?

**Comment by tgjones** [comment]
Closing this for now, but feel free to re-open if you're still experiencing the issue and can send me the shader file that's causing the problem.
