### ISSUE TITLE
Macro argument in UNITY_FOG_COORDS(1) disappear when formatting

### ISSUE THREAD

**Issue by emilberwald** [tgjones/HlslTools#197]
Macro argument for UNITY_FOG_COORDS(1) disappears for some reason after pressing Ctrl K + Ctrl D

Minimal example should be something like:

shadertoolsconfig.json:
`{
  "hlsl.preprocessorDefinitions": { },
  "hlsl.additionalIncludeDirectories": [
    "C:/Program Files/Unity/Hub/Editor/2020.1.9f1/Editor/Data/CGIncludes"
  ]
}`

`#include "UnityCG.cginc"

struct OUTPUT
{
    UNITY_FOG_COORDS(1)
};`

**Comment by tgjones** [comment]
Thanks for reporting this 👍

**Comment by Ph0t0nX** [comment]
How are you guys getting it working with the .shader files?

**Comment by emilberwald** [comment]
> How are you guys getting it working with the .shader files?

I #include .hlsl files to be able to separate unity-specific stuff with general shader stuff.
