### ISSUE TITLE
Formatting of semantics

### ISSUE THREAD

**Issue by chaoticbob** [tgjones/HlslTools#198]
This plug-in is amazing! It's has helped me trim down a a lot of development time for shaders. Thank you for making it. 

I looked through the issues but I couldn't find this but I might have just missed. Is it possible to disable automatic formatting of semantics? I'm a bit pedantic about the alignment of semantics and keeping things readable.

Currently when the autoformatting  turns this:
```
float4 Position : POSTION;
float3 Normal   : NORMAL;
float2 UV       : TEXCOORD;
```
into this:
```
float4 Position : POSTION;
float3 Normal : NORMAL;
float2 UV : TEXCOORD;
```

It's not the end of the world but it would be nice if the autoformatting either 1) didn't change this or 2) if there's an option for it to align on the `:`.

**Comment by tgjones** [comment]
> Thank you for making it.

You're welcome!

This is a good feature suggestion. I'll have a think about which option makes the most sense, but making it optional somehow is definitely a good idea.

**Comment by tgjones** [comment]
I've added an option for this:

![image](https://user-images.githubusercontent.com/102049/102022133-b2352b00-3d7c-11eb-8af1-2d1de025d910.png)

Arguably this "don't change" setting should be available for the other spacing options too.
