### ISSUE TITLE
Support non-root virtual directory mappings

### ISSUE THREAD

**Issue by pbbastian** [tgjones/HlslTools#204]
Unity has a virtual file system for packages that supports include paths like this:
```hlsl
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
```
Internally, `Packages/com.unity.render-pipelines.universal` is mapped to the actual folder of the package, which could be in the PackageCache, embedded in the Packages folder, or mapped directly to any folder. 

HLSL Tools supports virtual directory mappings, and these could be used to map the path to the correct folder. However, it requires the virtual directory to be a root path -- i.e. start with `/` -- which the Packages folder isn't.

**Comment by zongsheng-zhao** [comment]
I have created a fork to solve this issue. Now it's under pull request #232
