### ISSUE TITLE
InstanceID() is not declared.

### ISSUE THREAD

**Issue by Hearwindsaying** [tgjones/HlslTools#209]
According to HLSL reference: https://docs.microsoft.com/en-us/windows/win32/direct3d12/instanceid

It should be **InstanceID()** instead of **InstanceId()**?

![image](https://user-images.githubusercontent.com/42607989/118217035-3ebc5480-b4a7-11eb-9583-6d911c1852f5.png)

**Comment by tgjones** [comment]
Thanks for the bug report!
