### ISSUE TITLE
Intellisense not working properly in Visual Studio 2022

### ISSUE THREAD

**Issue by mr-phazer** [tgjones/HlslTools#219]
When using the plugin in VS 2020, the syntax highlighting works fine, and intellisense can detect if I write a wrong member in a float4 variable for example, but  "show member" and auto-complete is not working.

Thank you so very much for this tool that makes HLSL editing a delight:)

**Comment by RockyGitHub** [comment]
This is occuring for me as well on VS 2022

**Comment by tgjones** [comment]
This is fixed now.
