### ISSUE TITLE
uint64_t and crew unsupported

### ISSUE THREAD

**Issue by Nielsbishere** [tgjones/HlslTools#246]
This also includes vectors of uint64_t such as uint64_t2.

**Comment by alecazam** [comment]
I'm seeing  u/int64_t2/3/4, u/int16_t2/3/4, float64_t2/3/4 all flagged as invalid types.   I mostly care about the ints, since double support is so poor in HLSL.  I'm trying to create a MSL/HLSL generator.

**Comment by Nielsbishere** [comment]
My bad, read it the wrong way. Thought you said "as valid types".

**Comment by Nielsbishere** [comment]
@alecazam If you want the support, my branch has it right now 🎉:
![afbeelding](https://user-images.githubusercontent.com/28758736/228610266-3e38f1be-45c4-4f2a-8741-6d2546245aaf.png)
All unit tests are passing, so I'll be making a PR for this.

**Comment by Nielsbishere** [comment]
https://github.com/tgjones/HlslTools/pull/249

**Comment by tgjones** [comment]
Implemented by #249.

**Comment by Nielsbishere** [comment]
Awesome thanks 👌
