### ISSUE TITLE
Can I turn off the preprocessor grey out

### ISSUE THREAD

**Issue by hackershi** [tgjones/HlslTools#248]

**Comment by BenSimsTantalus** [comment]
I'd also like this option. It makes editing Unreal shaders a pain without adding lots of custom defines to a json file.

**Comment by tgjones** [comment]
Implementing this would require quite large changes to the parser and syntax highlighting code. At the moment the greyed out code simply isn't parsed at all, which is why it isn't syntax-highlighted.
