### ISSUE TITLE
Make SourceFieldSymbol public?

### ISSUE THREAD

**Issue by amerkoleci** [tgjones/HlslTools#28]
Hi,
I'm using SourceFieldSymbol to access Syntax property (VariableDeclaratorSyntax), would be possible to make it public, no need public constructor.

Thank you

**Comment by tgjones** [comment]
Yes, no problem. I don't see why those `Symbol` subclasses shouldn't be public.

Do you need access to `IntrinsicTypes`? I was considering making it `internal`.

**Comment by amerkoleci** [comment]
No I dont have, please update System.Collection.Immutable nuget package to latest 1.1.37.0 too

**Comment by amerkoleci** [comment]
Note also that HlslTools.csproj has "System.Runtime" path pointing too "..\..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Runtime.dll"

**Comment by tgjones** [comment]
I've made all the `Symbol` classes `public`, with `internal` constructors. I've upgraded System.Collections.Immutable to 1.1.37, and removed the errant reference to System.Runtime.dll.

**Comment by amerkoleci** [comment]
Thank you
