### ISSUE TITLE
Macros does not work with #ifdef

### ISSUE THREAD

**Issue by amerkoleci** [tgjones/HlslTools#33]
I have added my defined by accessing:
options.PreprocessorDefines.Add("VERTEX_COLOR")

Then in my shader if I have #if VERTEX_COLOR it works, but if I have #ifdef VERTEX_COLOR does not work.

**Comment by tgjones** [comment]
I can't repro this. For me, it works whether I use `#if`, `#ifdef`, or `#if defined(...)`.

Can you point me to a sample project where I can see the bug?

**Comment by amerkoleci** [comment]
File ConstantBuffers.fxh
`
#ifndef MAX_LIGHTS_PER_PASS
#	define MAX_LIGHTS_PER_PASS 4
#endif

// Constant Buffers
cbufferPerCamera : register(b0)
{
	row_major float4x4 ViewProjection : packoffset(c0);
};
`

File MyEffect.fx
`
#include "ConstantBuffers.fxh"

struct VSInput
{
	float4 Position : POSITION;
#ifdef VERTEX_COLOR
	float4 Color : COLOR0;
#endif
}

`

I have in my C# project call to:
options.PreprocessorDefines.Add("VERTEX_COLOR")

**Comment by tgjones** [comment]
I notice a couple of syntax errors there:

1. `cbufferPerCamera` should be `cbuffer PerCamera`.
2. The `VSInput` struct declaration should end with a semicolon.

After fixing those syntax errors, I still can't repro the macro `#ifdef` problem.

**Comment by tgjones** [comment]
Can you also try adding `#define VERTEX_COLOR` to the top of the shader, to make sure that that simple case works?

**Comment by amerkoleci** [comment]
Was github type error, seams that define of MAX_LIGHTS_PER_PASS breaks defines, I will try to reproduce.

**Comment by tgjones** [comment]
Closing for now, feel free to re-open if you can repro the issue.
