### ISSUE TITLE
Errors appear when accessing namespace members

### ISSUE THREAD

**Issue by sjschaff** [tgjones/HlslTools#38]
As an example, the following code snippet produces the errors on the line assigning 'bar':

Found ';' but expected '('.
Invalid expression term ';'
Found ';' but expected '<identifier>'.
Found ';' but expected ')'.

```
namespace NS
{
    static const int foo = 4;
}

void main()
{
    int bar = NS::foo;
}
```

**Comment by tgjones** [comment]
Thanks! This is fixed now, it will be included in the next VS Gallery release.
