### ISSUE TITLE
Feature: Add support for min16<type>types

### ISSUE THREAD

**Issue by adamrankin** [tgjones/HlslTools#48]
Hello!

First off, thanks for the extension, I'm a big fan.

My request is to add support for the min16float3(etc...) types. I'm using VS2015 and HLSLTools and they are not recognized.

**Comment by adamrankin** [comment]
Apologies, I just browsed commits and saw [7a2a3e640f322c8354d7bb2e1c7d4c852d3a5e67](https://github.com/tgjones/HlslTools/commit/7a2a3e640f322c8354d7bb2e1c7d4c852d3a5e67)!

Will this be packaged into an updated download through the Extension Manager in Visual Studio?

**Comment by tgjones** [comment]
No apology necessary! Yes, I will be releasing a new version soon - probably not this week, but imminently.
