### ISSUE TITLE
Not handling ##

### ISSUE THREAD

**Issue by reltham** [tgjones/HlslTools#5]
Reports "Found '##' but expected '#'."

 ## is valid in HLSL preprocessor.

**Comment by reltham** [comment]
Also sometimes gets reported as "Unexpected token '##'."

**Comment by tgjones** [comment]
It does - or at least, it's supposed to - handle `##`, but clearly not in all cases. Can you give an example of a macro where you're getting that error?

**Comment by reltham** [comment]
It may be getting into a bad state because of the other issues I reported. Or it might be some combination.

I'll get you an example tomorrow when I get into work (it's with a work solution).

**Comment by tgjones** [comment]
Thanks for the example you sent through. I have found at least one problem: I'm not correctly handling `##` when used in a macro call; only when used in a macro definition. I'll fix that first and then see if that clears up the remaining issues.

**Comment by reltham** [comment]
Glad the example helped.  Really glad you made this tool, and happy to help find bugs so you can stomp them.

**Comment by tgjones** [comment]
I have improved the situation somewhat. This now works:

``` c
#define FOO 1
#define PARAM(type, name) type name
PARAM(float, Transparency##FOO);
```

But this doesn't - HLSL Tools reports an unexpected token '##':

``` c
#define FOO
#define PARAM(type, name) type name
PARAM(float, Transparency##FOO);
```

... and the HLSL compiler actually agrees with that error. It seems like you can't use `##` with a macro without a value. (At least, not in that specific context - oddly, it works in other situations.)

In your example code, you have something like (obviously your macro name is different):

``` c
#ifndef FOO
#define FOO
#endif
```

I assume that when you actually compile these shaders, you externally define `FOO`. But to get HLSL Tools to work with this, you'll need to change it to:

``` c
#ifndef FOO
#define FOO 0 // or any value at all
#endif
```

This is at the edges of my preprocessor knowledge, so please correct me if you think I made a mistake.

**Comment by tgjones** [comment]
> Really glad you made this tool, and happy to help find bugs so you can stomp them.

Thanks :) And thank you for taking the time to log these bugs.

**Comment by reltham** [comment]
The example I gave you compiles as is with no external defines passed in at compile time.  We have other shaders that include that fxh but define the 'FOO' to something beforehand.

We compile with fxc.exe version:
Microsoft (R) Direct3D Shader Compiler 9.29.952.3111
Copyright (C) Microsoft Corporation 2002-2009. All rights reserved.

The only params we use are /Tfx_2_0 and /Zi.

My understanding is that x##y only needs to be a valid token once combined, so y can be blank as long as x is something.  The y has to be 'defined' to avoid errors, hence the #ifundef bit.

**Comment by tgjones** [comment]
So, this is pretty weird: I think there may be a bug in the HLSL compiler. This works:

``` c
#define FOO
#define PARAM(type, name, semantic) type name: semantic
PARAM(float, bar##FOO, Bar) = 1.0f;
```

... but this doesn't (says "unexpected token '##'"):

``` c
#define FOO
#define PARAM(type, name) type name
PARAM(float, bar##FOO) = 1.0f;
```

Anyway, this is a rabbit hole :) I'll just implement it in the way I think it should work, which is as you described.

**Comment by tgjones** [comment]
I asked a contact on the HLSL compiler team about this, and it turns out there *is* a bug in the HLSL compiler :) The fact that this works is, apparently, a bug:

``` c
#define FOO
#define PARAM(type, name, semantic) type name: semantic
PARAM(float, bar##FOO, Bar) = 1.0f;
```

The `##` token pasting operator should only be allowed in a macro body context, which would match the VC++ compiler.

So I'm going to stick with what the HLSL compiler's behaviour "should" be, not what it is, and not add support for the `##` operator in macro arguments. I realise that's not the only way to go; but for the sake of my sanity, I don't want to start supporting all the various foibles of the HLSL compiler :)

Unfortunately, this workaround doesn't... work (the HLSL compiler gives a syntax error, and VC++ compiles it but the resulting variable is named `barFOO`, not `bar`):

``` c
#define FOO
#define PASTE(x, y) x##y
#define PARAM(type, name, semantic) type name: semantic
PARAM(float, PASTE(bar, FOO), Bar) = 1.0f;
```
