### ISSUE TITLE
Please don't enforce a specific brace style.

### ISSUE THREAD

**Issue by khatharr** [tgjones/HlslTools#51]
I really love this plugin, but it moves my braces all the time and it really drives me up the wall.

Could we get an option in the settings to disable this behavior?

Thank you for the plugin!

**Comment by tgjones** [comment]
Thanks for the feedback, and glad you find HLSL Tools useful.

So it looks like added this enum, but then for some reason I've now forgotten didn't hook it up:
https://github.com/tgjones/HlslTools/blob/160eb70f6d6fdf40be6be0d0c688bb5d3cada530/src/ShaderTools/Hlsl/Formatting/FormattingOptions.cs#L90

I don't see why it should be a problem, so I'll take a look at this for the next release.

**Comment by khatharr** [comment]
Thanks!

**Comment by tgjones** [comment]
Implemented, with similar settings to Visual C++.
