### ISSUE TITLE
Error with function declared in macro

### ISSUE THREAD

**Issue by simontaylor81** [tgjones/HlslTools#59]
I'm seeing some rather confusing behaviour when I have a preprocessor macro that defines a function. The most obvious issue is that the Intellisense gives an error saying the function is not declared:

![errortooltip](https://cloud.githubusercontent.com/assets/6118315/22083645/43b29d1a-ddcd-11e6-9d2b-73d3e311010a.png)

Then, if I hover over the declaration in the macro, the tooltip is all screwy:

![badtooltip](https://cloud.githubusercontent.com/assets/6118315/22083687/78c67e7c-ddcd-11e6-992a-8b0d3b54b08b.png)

Then, if I manually declare the function as well, it (correctly) gives a re-definition error. So obviously it was able to parse the macro and expand the definition, but for whatever reason it isn't found at the callsite.

![redefinitionerror](https://cloud.githubusercontent.com/assets/6118315/22083786/cdbe3a14-ddcd-11e6-986a-df0ae16bd676.png)

I did have a quick go at debugging this, and there seems to be some oddities for the names of identifiers for things that have been expanded from macros, but it could just be me misunderstanding. I'm afraid I then got a bit lost and gave up :(.

I'm using the latest preview version from vsixgallery, 1.0.146, but the behaviour appears to be unchanged from the previous version I was using (don't know what that was though).

Here's the file that reproduces the problem:
[FunctionMacroRepro.zip](https://github.com/tgjones/HlslTools/files/715078/FunctionMacroRepro.zip)

**Comment by tgjones** [comment]
If only all bug reports were as clear as this one :)

Should be fixed now - please give v1.0.170 a try.

**Comment by simontaylor81** [comment]
Yup, works perfectly! Thanks.
