### ISSUE TITLE
Intellisense shown in comments

### ISSUE THREAD

**Issue by simontaylor81** [tgjones/HlslTools#60]
Very minor thing, but the intellisense autocomplete window pops up when typing a comment, which is a bit distracting.

![commentintellisense](https://cloud.githubusercontent.com/assets/6118315/22084069/e5f5bbd8-ddce-11e6-93dd-b849ad500c86.png)

**Comment by tgjones** [comment]
I can't repro this - probably it's been fixed in the intervening time. If you can repro it, please re-open.
