### ISSUE TITLE
Test OutliningTaggerTests.CanDoTagging fails when there's no outline block in file

### ISSUE THREAD

**Issue by OndrejPetrzilka** [tgjones/HlslTools#63]
Example content of test file:
`RWBuffer<uint> BoundingBox : register(u2);`

Result:
Assert.NotEmpty() Failure

https://github.com/tgjones/HlslTools/blob/ec20ab412893563d92045f9e150f17c0f22004e0/src/ShaderTools.Editor.VisualStudio.Tests/Hlsl/Tagging/AsyncTaggerTestsBase.cs#L38
```
    if (MustCreateTagSpans)
        Assert.NotEmpty(tagSpans);
```

**Comment by tgjones** [comment]
Fixed in 967c185920923ad59fc9b056ca3dc5126beae851 - I've removed the useless test that was there before, and added an actual test.
