### ISSUE TITLE
Avoid C# 7.0 semantics?

### ISSUE THREAD

**Issue by amerkoleci** [tgjones/HlslTools#69]
Is possible to not make usage of preliminary C# 7.0 usage? 
Otherwise I'm not able to build it using VS 2015.

**Comment by tgjones** [comment]
I guess I can do that until VS2017 RTMs. But there's a lot of syntactic goodness in C# 7 that I'm looking forward to using...

**Comment by tgjones** [comment]
I've removed use of C# 7 syntax, at least until VS2017 RTMs. I can't promise I'll hold out much longer than that though...
