### ISSUE TITLE
"typedef" makes VS2015 IDE crashed

### ISSUE THREAD

**Issue by fesdobat** [tgjones/HlslTools#74]
typedef VS_OUTPUT PS_INPUT;

"typedef" is OK with D3D11 shader compiler; 
but when I'm trying the hlsl tool and get it installed,
I open a .hlsl file including "typedef", 
and then the VS IDE get crashed.

**Comment by tgjones** [comment]
By coincidence, I think I fixed that exact issue earlier today (#64).

Please could you try v1.0.180 from here, and let me know if you still have the crash?
http://vsixgallery.com/extension/7def6c01-a05e-42e6-953d-3fdea1891737/

**Comment by fesdobat** [comment]
OK, It's now fixed with v1.0.180.
thank you.
