### ISSUE TITLE
= symbol not reconized by the auto-indentation

### ISSUE THREAD

**Issue by Melcx** [tgjones/HlslTools#76]
Hi,

First, thanks for this fantastic plugin !

Then here is my (little) problem : the '=' symbol seem to not be recognized by the auto-indentation as a binary operator. I would like to auto-indent this (look at the spaces) : 
`int a =10* b;`
into this : 
`int a=10*b;`  (no spaces)
But by disabling the spaces between binary operators in the HLSL Tool's options, it gives me this :
`int a = 10*b;` (spaces around '=')

Thanks for advance !

**Comment by tgjones** [comment]
Thanks for reporting this - I'll aim to fix it in the next version.

**Comment by tgjones** [comment]
Actually C# is the same as HLSL Tools - it doesn't apply binary operator formatting rules to `=`. This isn't a common request, so I'm going to close it, but I'd accept a PR that adds an additional formatting option for "Ignore spaces in declaration statements", to match C#'s rule of the same name.
