### ISSUE TITLE
mad intrinsic is documented incorrectly

### ISSUE THREAD

**Issue by ajmiles** [tgjones/HlslTools#78]
> allFunctions.AddRange(Create3(
>                 "mad",
>                 "Performs an arithmetic multiply/add operation on three values.",
>                 IntrinsicTypes.AllNumericTypes,
>                 "m", "The multiplication value.",
>                 "a", "The first addition value.",
>                 "b", "The second addition value."));

A multiply-add has two multiplication values and one addition value, not the other way around.

**Comment by tgjones** [comment]
Thanks, I've fixed this - but I actually copied this from https://msdn.microsoft.com/en-us/library/windows/desktop/ff471418(v=vs.85).aspx, so you might want to also talk to whoever owns the HLSL docs :)
