### ISSUE TITLE
Support typedef semantics

### ISSUE THREAD

**Issue by dustin-biser** [tgjones/HlslTools#81]
Currently the following valid hlsl typedef is not recognized by this extension

```c
struct VS_Output
{
    float4 position : SV_POSITION;
    float2 texCoord : TEXCOORD;
};
typedef VS_Output PS_Input;
```
Currenlty `typedef` is not recognized as a keyword and `PS_Input` is not recognized as a type.

**Comment by tgjones** [comment]
Which version are you using? I added `typedef` support quite recently, but the latest version on the Marketplace (at the time of writing, v1.1.197) should work correctly with your example. Please re-open if that's not the case.

Although it should be parsed correctly, I have just noticed though that `typedef` wasn't being highlighted correctly, and neither were the aliased types, so I've just fixed that.
