### ISSUE TITLE
Count preprocessor blocks as scopes

### ISSUE THREAD

**Issue by cmartel** [tgjones/HlslTools#88]
In larger "master" shader files, preprocessor blocks (i.e.: #if DEFINE) can quickly accumulate and nest together. Even with comments on #endifs identifying where each block ends, it can grow unyieldy. Without scope information, it can be hard to tell what's in scope or not even when using config files or __INTELLISENSE__ macros to wrangle defines. 

Some way of treating these preprocessor directives as scopes would make it possible to tell at a glance which preprocessor block code currently is. Barring that, at the very least, being able to collapse/expand preprocessor blocks as VS does with C++ (or HLSL files treated as C++) would help hiding extraneous information while working.

**Comment by tgjones** [comment]
I think making preprocessor conditionals collapsible absolutely makes sense, thanks for the suggestion.

> Some way of treating these preprocessor directives as scopes would make it possible to tell at a glance which preprocessor block code currently is.

Can you elaborate a bit more on what UI you're imagining for this? I don't fully understand what you mean.

**Comment by cmartel** [comment]
Sure, here's a random sample from UE4:
![image](https://cloud.githubusercontent.com/assets/302493/25565708/77ce04f0-2d9a-11e7-86a7-e71fa67e1f7b.png)

With the editing caret inside the WRITES_VELOCITY_TO_GBUFFER block, it'd be nice to have some way of seeing what preprocessor block I'm inside in the scope dropdown menu:

![image](https://cloud.githubusercontent.com/assets/302493/25565719/c2e56668-2d9a-11e7-9e6a-893c8614b5ea.png)

Unreal shaders are relatively clean, but my work shader base is a convoluted hierarchy of nested #ifdef blocks, sometimes reaching 4-5 defines deep with the parent one being dozens of source lines earlier. In that context, it's really hard to see where I actually am.

The scope navigation menu was just the most intuitive thing that came to mind, it doesn't really make perfect sense to include preprocessor blocks in there. But one way or another, being able to visualize the hierarchy of preprocessor blocks at a glance would be a huge workflow improvement.

The alternative mentioned is what the C++ editor does for preprocessor blocks, treat them as #regions:
![image](https://cloud.githubusercontent.com/assets/302493/25565802/883a991e-2d9c-11e7-98ab-8b905e392bdd.png)

Then you can just collapse the defines that aren't relevant, but again, with many nested levels, that can become a game of trial and error. (Our shaderbase makes the questionable decision not to indent preprocessor blocks... A lot of these workflow issues stem from questionable decisions. ;))

**Comment by tgjones** [comment]
Only took 2.5 years, but this is implemented now...

![image](https://user-images.githubusercontent.com/102049/71328387-673c5b00-250e-11ea-9ae5-96e2dacd9dc6.png)
