### ISSUE TITLE
Makes VS unable to save files after a few minutes

### ISSUE THREAD

**Issue by RyanTorant** [tgjones/HlslTools#89]
After using the editor for a few minutes, the typing becomes slow and after that vs won't save files. Have to exit and re-open for it to work again, and changes are lost.

Visual Studio 2015 Update 3 Community
Windows 10 x64 Creators Update
Xeon E5-2683 V3
32 GB RAM

**Comment by tgjones** [comment]
@RyanTorant thanks for letting me know about this. It's obviously pretty bad when a text editor extension causes you to be unable to save files! I've been working on a fix, and I've got one ready: please could you download v1.1.235 (or later, depending on when you read this) from here:

http://vsixgallery.com/extension/7def6c01-a05e-42e6-953d-3fdea1891737/

and give it a try? I think it should fix the issues you mentioned, but it would be great if you could confirm that.

**Comment by RyanTorant** [comment]
Ok, I did some quick tests and it appears to work now.
Will get back to you after using it for a longer time.

Glad to see such a quick fix

**Comment by tgjones** [comment]
That's good news - please let me know how you get on, if you have a chance to test it more. I'm planning to release this version to the Marketplace in the next couple of days.

**Comment by RyanTorant** [comment]
Well, can confirm that the problem is gone.
Thanks, this tool is awesome.
