### ISSUE TITLE
Crashes Visual Studio opening large file.

### ISSUE THREAD

**Issue by RyanTorant** [tgjones/HlslTools#90]
The extension makes Visual Studio crash a few seconds after opening a specific, relatively large file (~500 lines, plus includes and macros), every time the file is opened.

Visual Studio 2015 Update 3 Community
Windows 10 x64 Creators Update
Xeon E5-2683 V3
32 GB RAM
This version of the extension : http://vsixgallery.com/extension/7def6c01-a05e-42e6-953d-3fdea1891737/

**Comment by tgjones** [comment]
Are you able to send me (here, if you don't mind it being public, or to my email address - tim@timjones.io - if you prefer it kept private) the shader that causes the problem?

I've tested with a number of large files, and I haven't had this kind of problem, so I think there must be something specific to that file.

**Comment by anuwat82** [comment]
I have same experienced crashing for editing my large hlsl code too.

**Comment by tgjones** [comment]
@anuwat82 are you able to send me the HLSL file that crashes? If you're able to email it to me, I will of course keep it private.

**Comment by anuwat82** [comment]
@tgjones I sent you a hlsl to recreate the crash problem. Please your email.

**Comment by anuwat82** [comment]
update:
the problem seems disappear with version 1.1.261 .

**Comment by RyanTorant** [comment]
Update : Seems to be fixed on 1.1.266

**Comment by anuwat82** [comment]
after using 1.1.266 for a day, the problem seems disappear.

**Comment by tgjones** [comment]
Closing this as the problem seems to be fixed - please re-open if it's still crashing.
