### ISSUE TITLE
Is there a way to use HLSL tools with Unity?

### ISSUE THREAD

**Issue by Lex-DRL** [tgjones/HlslTools#92]
The last commit in ["unity" banch](https://github.com/tgjones/HlslTools/commits/unity) was almost a year ago, with no stable release yet.
Are there any plans to continue developing it in the nearest future?

If not, is there any workaround to avoid the most crucial errors at least in the CG part of Unity shaders with [the current stable version of HLSL tools](https://marketplace.visualstudio.com/items?itemName=TimGJones.HLSLToolsforVisualStudio)? 
By errors I mean a lack of:
* Support for the basic types like **fixed**
* A way to specify a folder with Unity's built-in cginc files (so **#include "UnityCG.cginc"** won't highlight as an error and will also provide all the built-in functions/structs/macros).
* Support for including cginc files by a path relatively to project root. So that **#include "Assets/Shaders/MyFile.cginc"** will work.
* Support for preprocessor directives like **#if defined(FOO)**.

The whole ShaderLab part is not as important. After all, you can extract the entire CG code to the external cginc file, if you don't want to see errors. But inability to include cgincs and the lack of support for internal types devalues all the benefits of this amazing extention for Unity-shader development  :disappointed_relieved: .

**Comment by tgjones** [comment]
Hi @Lex-DR!

> Are there any plans to continue developing it in the nearest future?

Yes - if you look in the master branch, you'll see lots of ShaderLab-related activity in the last few days and weeks. I've also been [posting some screenshots on Twitter](https://twitter.com/_tim_jones_/status/867059874777182209):

![](https://pbs.twimg.com/media/DAhp2VEXgAEgbAP.jpg)

However, there's still more to do before ShaderLab support is fully baked, so in the meantime:

* You can use the recently added [`shadertoolsconfig.json` feature](https://github.com/tgjones/hlsltools#custom-preprocessor-definitions-and-additional-include-directories) to specify an additionai `#include` path to a folder of Unity's built-in cginc files (i.e. `C:\Program Files\Unity\Editor\Data\CGIncludes`)
* If you place a `shadertoolsconfig.json` file in your project root folder, with an `"hlsl.additionalIncludeDirectories"` entry of `"."`, it will resolve `.cginc` files relative to the project root.
* Once you're including the built-in `.cginc` files, you should get support for `fixed` etc. (I think they're `typedef`d or `#define`d somewhere in those files)
* Preprocessor directives are already supported - what behaviour are you seeing / not seeing? If you want to define some values to get IntelliSense working, you can [wrap them in an `__INTELLISENSE__` macro](https://github.com/tgjones/hlsltools#preprocessor-support).

Hopefully that helps. And keeps you going until full ShaderLab support arrives 😄

**Comment by Lex-DRL** [comment]
Hey @tgjones!
Thanks for the response, great news!


### Macros
> Preprocessor directives are already supported - what behaviour are you seeing / not seeing?

Autocompletion doesn't work. No suggestions appear, even if I have a macro/keyword defined a few lines above.
![000](https://cloud.githubusercontent.com/assets/3897975/26518092/196b7646-42b1-11e7-9c59-55272b483d0b.png)
Even compiler directives themselves are not completed. (ifdef, undef, define etc.):
![000](https://cloud.githubusercontent.com/assets/3897975/26518100/53ed9038-42b1-11e7-9ad0-4a3787b02989.png)

I tried Ctrl+Space, too. It works fine (with no hotkey) in other parts of code, but not with compiler directives.
![000](https://cloud.githubusercontent.com/assets/3897975/26518111/9933534e-42b1-11e7-9f8d-aa129aa59a38.png)


### Included file paths
> If you place a shadertoolsconfig.json file in your project root folder, with an "hlsl.additionalIncludeDirectories" entry of ".", it will resolve .cginc files relative to the project root.

Unfortunately, it doesn't. :disappointed: 
I put `shadertoolsconfig.json` with the following code to my root project folder:
```
{
  "hlsl.additionalIncludeDirectories": [
    "." // Directory containing this config file
  ]
}
```
![000](https://cloud.githubusercontent.com/assets/3897975/26518142/b5327740-42b2-11e7-8180-594a18f736bb.png)
And the file I'm including do exist on the disk:
![000](https://cloud.githubusercontent.com/assets/3897975/26518168/5010b0b0-42b3-11e7-8878-74a720bd7a2b.png)
And shader works perfectly fine in the Unity itself (no compile errors/warnings).
But HLSLtools can't find this cginc:
![001](https://cloud.githubusercontent.com/assets/3897975/26518186/b1316e70-42b3-11e7-939c-eb5ea2748122.png)
However, Unity's built-in CGINC folder is detected properly when I add `shadertoolsconfig.json` which point to it's absolute path:
```
{
  "hlsl.additionalIncludeDirectories": [
    "C:\\1-CG\\Unity\\5.6.1f1\\Editor\\Data\\CGIncludes"
  ]
}
```


Finally, do you have a semi-stable (beta?) release for the version of HLSLTools with Unity support? Even partial support of ShaderLab stuff would be great (Pass/Subshader/CGPROGRAM blocks).
I couldn't find it anywhere: not here, nor at the VS marketplace. And I have no experience developing VS extentions, so I'm not even sure if I can build it myself from sources. ["Build your first extension" tutorial page](https://www.visualstudio.com/en-us/docs/integrate/extensions/get-started/node) tells in the prerequisites block that I need a **Visual Studio Team Services account**, among with plenty of other stuff. But I don't seem to have one, I'm using a Community edition of VS.

P.S.: I've always been using Notepad++ for shader development, because formerly the only thing any VS extention was adding is just a syntax highlight. With no completion/IntelliSense. So no benefit over N++, but VS loads extremely longer.
However your extention changes the game entirely. Great job, already. :+1: 

I'm going to create a training course about unity shader programming in the nearest future. And it'd be awesome if there will be at least somewhat-working release of Unity-HLSLTools, so I could show the process in VS instead of N++.
No pressure, just explaining why I'm so impatient/excited about your ext :wink:

**Comment by tgjones** [comment]
* Macro names: I've logged this as #93. Macros are parsed correctly (AFAIK), so you shouldn't get any syntax errors, but you're right that there's no IntelliSense for them either. (Actually that's not true, you do get Quick Info hover tooltips, but not automatic completion.)

* Include file paths: It turns out that you can't actually put comments in `shadertoolsconfig.json` files, so my example in the readme was wrong (I've updated it). If you remove the `// Directory...` comment, it should work.

* Beta: No, ShaderLab support is not yet in the nightly build (i.e. the one [here on vsixgallery.com](http://vsixgallery.com/extension/7def6c01-a05e-42e6-953d-3fdea1891737/). This is beacuse it's still missing very basic functionality, specifically correctly updating the parent ShaderLab text buffer and nested HLSL buffers, when the contents change. This is a basic requirement, but actually really hard - probably the hardest challenge in all the work to support ShaderLab, just because the underlying Visual Studio APIs are both quite advanced and poorly documented. I'm getting close to tackling that problem, but until that's done, I won't enable ShaderLab in nightly builds. (The screenshot above cheated a little: ShaderLab support is pretty good already, as long as you don't actually, err, type anything.) For the same reason, it wouldn't help to build it from GitHub source yourself, because it's not at all usable yet.

I don't want to give an estimate on when the first nightly build with ShaderLab support will be ready, because I've done that before on other open source projects and been wildly wrong. But it is what I'm working on most evenings (after my little one goes to bed, so "evening" is a bit of an exaggeration). I'm going to get it finished as soon as I can.

**Comment by Lex-DRL** [comment]
Ok, then I'm looking forward to the stable release with Unity support.
After I removed the comment from `shadertoolsconfig.json` file, it indeed started to work. Yaay! :smile: 
Thanks for all your help and being so responsive.

P.S.: after all my cgincs started to work, I've found one extra area of improvement: #94. It's totally minor, so my duty is to request it, and it's up to you to decide whether it worth implementing or not.

**Comment by tgjones** [comment]
Thanks, #94 would be a nice enhancement.

I'm going to close this issue: ShaderLab support is in progress, but it's not really necessary to track such a large feature with a single issue like this one.

**Comment by Alan-FGR** [comment]
Hi guys,
This extension isn't being used for .shader files, is there a setting for that or is that only available in the Unity branch?
Thanks

**Comment by Alan-FGR** [comment]
Hi guys,
Is there a setting to make this extension work with .shader files or is that only available in the Unity branch?
Thanks

**Comment by Ph0t0nX** [comment]
> Hi guys,
> Is there a setting to make this extension work with .shader files or is that only available in the Unity branch?
> Thanks

Yeah... I agree - I installed it, hoping to be able to get auto-completion for .shader files... but nothing happens and my guess is that it doesn't recognize the .shader extension?
