### ISSUE TITLE
Completion issue : Types that are not declared yet are already accessible

### ISSUE THREAD

**Issue by mrvux** [tgjones/HlslTools#95]
Let's take the simple shader example : 

``` hlsl
Texture2D InputTexture;

float4 PS(psInput input) : SV_Target
{
    float4 color = 1.0f;
    return color;
}
```

typing "I "above `InputTexture` adds it to suggestion, which is invalid since it is not declared yet (will trigger a compiler error). Also since we are not inside a function, this variable can't be used anyway.

![image](https://cloud.githubusercontent.com/assets/272494/26529859/389e02c4-43d1-11e7-8a57-990336e5469e.png)

On the same aspect, using the same shader code, if we are inside the PS scope, and try to access color befor it is declared, it's is also in suggestion list, as per the screenshot:

![image](https://cloud.githubusercontent.com/assets/272494/26529868/73e4bb16-43d1-11e7-9ff8-9211dfac9512.png)

**Comment by tgjones** [comment]
Fixed by #96.
