### ISSUE TITLE
Can't full disable "auto-indentation"

### ISSUE THREAD

**Issue by JSeb-92** [tgjones/HlslTools#99]
I've disabled all 3 formatting options (auto_format on ';' on '}' and on paste).
But auto-indentation still occurs when I close brace: ')', I've to press 'esc' to get my formatting back.
Could you add another option for this closing brace ')' please ?
Thanks

**Comment by JSeb-92** [comment]
This issue also occurs with the '{' key: it always auto_format following lines.
I'll be great if I could disable theses 2 auto_format cases
Thanks

**Comment by tgjones** [comment]
I've added an option to disable formatting when typing closing parenthesis, as well as an option to disable all formatting when typing:

<img width="527" alt="formatting" src="https://user-images.githubusercontent.com/102049/60629018-ebc5e080-9deb-11e9-87cb-8a42b4bda51b.PNG">

**Comment by Reedbeta** [comment]
Has this fix made it into a release yet?
